package com.mirabilis.core.designsystem.token

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.mirabilis.core.designsystem.theme.MirabilisExtraColors

fun lightColorScheme(
    primary: Color = rawOliveLeaf,
    onPrimary: Color = semanticOnError,
    primaryContainer: Color = rawBrightFern,
    onPrimaryContainer: Color = neutralText,
    secondary: Color = rawSageGreen,
    onSecondary: Color = Color(0xFF1D1D1D),
    secondaryContainer: Color = rawBrightFern,
    onSecondaryContainer: Color = Color(0xFF1D1D1D),
    tertiary: Color = rawForestMoss,
    onTertiary: Color = Color(0xFF000000),
    tertiaryContainer: Color = rawTertiaryDark,
    onTertiaryContainer: Color = neutralText,
    error: Color = semanticError,
    onError: Color = semanticOnError,
    errorContainer: Color = semanticOnErrorDark,
    onErrorContainer: Color = Color(0xFFFFFFFF),
    background: Color = neutralBg,
    onBackground: Color = neutralText,
    surface: Color = neutralBg,
    onSurface: Color = neutralText,
    surfaceVariant: Color = neutralSurfaceVariant,
    onSurfaceVariant: Color = neutralOnSurfaceVariant,
    outline: Color = Color(0xFF5A604F),
    outlineVariant: Color = Color(0xFF8C9382),
    inverseSurface: Color = neutralText,
    inverseOnSurface: Color = neutralBg,
    inversePrimary: Color = Color(0xFF719040),
    surfaceBright: Color = neutralBg,
    surfaceDim: Color = neutralSurfaceVariant,
    surfaceContainerLowest: Color = neutralBg,
    surfaceContainerLow: Color = neutralSurfaceVariant,
    surfaceContainerHigh: Color = neutralOnSurfaceVariant,
    surfaceContainer: Color = neutralSurfaceVariant,
): androidx.compose.material3.ColorScheme = lightColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    outlineVariant = outlineVariant,
    surfaceContainer = surfaceContainer,
    surfaceContainerHigh = surfaceContainerHigh,
    surfaceContainerLow = surfaceContainerLow,
    surfaceContainerLowest = surfaceContainerLowest,
    surfaceBright = surfaceBright,
    surfaceDim = surfaceDim,
    inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface,
    inversePrimary = inversePrimary,
)

fun darkColorScheme(
    primary: Color = rawBrightFern,
    onPrimary: Color = Color(0xFF181E12),
    primaryContainer: Color = rawOliveLeaf,
    onPrimaryContainer: Color = neutralBg,
    secondary: Color = rawSageGreen,
    onSecondary: Color = Color(0xFF152015),
    secondaryContainer: Color = rawBrightFern,
    onSecondaryContainer: Color = Color(0xFF000000),
    tertiary: Color = rawTertiaryDark,
    onTertiary: Color = Color(0xFF2A3428),
    tertiaryContainer: Color = rawForestMoss,
    onTertiaryContainer: Color = Color(0xFF000000),
    error: Color = semanticErrorDark,
    onError: Color = semanticOnErrorDark,
    errorContainer: Color = semanticError,
    onErrorContainer: Color = Color(0xFFFFFFFF),
    background: Color = neutralBgDark,
    onBackground: Color = neutralTextDark,
    surface: Color = neutralBgDark,
    onSurface: Color = neutralTextDark,
    surfaceVariant: Color = neutralSurfaceVariantDark,
    onSurfaceVariant: Color = neutralOnSurfaceVariantDark,
    outline: Color = Color(0xFF828A78),
    outlineVariant: Color = neutralOnSurfaceVariantDark,
    inverseSurface: Color = neutralBgDark,
    inverseOnSurface: Color = neutralTextDark,
    inversePrimary: Color = rawBrightFern,
    surfaceBright: Color = neutralSurfaceVariantDark,
    surfaceDim: Color = neutralBgDark,
    surfaceContainerLowest: Color = neutralSurfaceVariantDark,
    surfaceContainerLow: Color = neutralBgDark,
    surfaceContainerHigh: Color = neutralSurfaceVariantDark,
    surfaceContainer: Color = neutralBgDark,
): androidx.compose.material3.ColorScheme = darkColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    outlineVariant = outlineVariant,
    surfaceContainer = surfaceContainer,
    surfaceContainerHigh = surfaceContainerHigh,
    surfaceContainerLow = surfaceContainerLow,
    surfaceContainerLowest = surfaceContainerLowest,
    surfaceBright = surfaceBright,
    surfaceDim = surfaceDim,
    inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface,
    inversePrimary = inversePrimary,
)

fun lightExtraColors(): MirabilisExtraColors = MirabilisExtraColors(
    warning = semanticWarning,
    onWarning = semanticOnWarning,
    success = semanticSuccess,
    onSuccess = semanticOnSuccess,
)

fun darkExtraColors(): MirabilisExtraColors = MirabilisExtraColors(
    warning = semanticWarningDark,
    onWarning = semanticOnWarningDark,
    success = semanticSuccessDark,
    onSuccess = semanticOnSuccessDark,
)
